//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4_Client.Lab4Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://KAA/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://KAA/", ConfigurationName="Lab4Service.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (AddMessage) сообщения AddMessage не соответствует значению по умолчанию (Add).
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/AddMessage", ReplyAction="*")]
        Lab4_Client.Lab4Service.AddMessage1 Add(Lab4_Client.Lab4Service.AddMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/AddMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.AddMessage1> AddAsync(Lab4_Client.Lab4Service.AddMessage request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (ConcatMessage) сообщения ConcatMessage не соответствует значению по умолчанию (Concat).
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/ConcatMessage", ReplyAction="*")]
        Lab4_Client.Lab4Service.ConcatMessage1 Concat(Lab4_Client.Lab4Service.ConcatMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/ConcatMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.ConcatMessage1> ConcatAsync(Lab4_Client.Lab4Service.ConcatMessage request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (SumMessage) сообщения SumMessage не соответствует значению по умолчанию (Sum).
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/SumMessage", ReplyAction="*")]
        Lab4_Client.Lab4Service.SumMessage1 Sum(Lab4_Client.Lab4Service.SumMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://KAA/SumMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.SumMessage1> SumAsync(Lab4_Client.Lab4Service.SumMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMessage", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class AddMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=1)]
        public int y;
        
        public AddMessage() {
        }
        
        public AddMessage(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMessageResponse", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class AddMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public int AddMessageResult;
        
        public AddMessage1() {
        }
        
        public AddMessage1(int AddMessageResult) {
            this.AddMessageResult = AddMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConcatMessage", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class ConcatMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=1)]
        public double d;
        
        public ConcatMessage() {
        }
        
        public ConcatMessage(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConcatMessageResponse", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class ConcatMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public string ConcatMessageResult;
        
        public ConcatMessage1() {
        }
        
        public ConcatMessage1(string ConcatMessageResult) {
            this.ConcatMessageResult = ConcatMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumMessage", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class SumMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public Lab4_Client.Lab4Service.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=1)]
        public Lab4_Client.Lab4Service.A a2;
        
        public SumMessage() {
        }
        
        public SumMessage(Lab4_Client.Lab4Service.A a1, Lab4_Client.Lab4Service.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumMessageResponse", WrapperNamespace="http://KAA/", IsWrapped=true)]
    public partial class SumMessage1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KAA/", Order=0)]
        public Lab4_Client.Lab4Service.A SumMessageResult;
        
        public SumMessage1() {
        }
        
        public SumMessage1(Lab4_Client.Lab4Service.A SumMessageResult) {
            this.SumMessageResult = SumMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Lab4_Client.Lab4Service.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Lab4_Client.Lab4Service.SimplexSoap>, Lab4_Client.Lab4Service.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client.Lab4Service.AddMessage1 Lab4_Client.Lab4Service.SimplexSoap.Add(Lab4_Client.Lab4Service.AddMessage request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            Lab4_Client.Lab4Service.AddMessage inValue = new Lab4_Client.Lab4Service.AddMessage();
            inValue.x = x;
            inValue.y = y;
            Lab4_Client.Lab4Service.AddMessage1 retVal = ((Lab4_Client.Lab4Service.SimplexSoap)(this)).Add(inValue);
            return retVal.AddMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.AddMessage1> Lab4_Client.Lab4Service.SimplexSoap.AddAsync(Lab4_Client.Lab4Service.AddMessage request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client.Lab4Service.AddMessage1> AddAsync(int x, int y) {
            Lab4_Client.Lab4Service.AddMessage inValue = new Lab4_Client.Lab4Service.AddMessage();
            inValue.x = x;
            inValue.y = y;
            return ((Lab4_Client.Lab4Service.SimplexSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client.Lab4Service.ConcatMessage1 Lab4_Client.Lab4Service.SimplexSoap.Concat(Lab4_Client.Lab4Service.ConcatMessage request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Lab4_Client.Lab4Service.ConcatMessage inValue = new Lab4_Client.Lab4Service.ConcatMessage();
            inValue.s = s;
            inValue.d = d;
            Lab4_Client.Lab4Service.ConcatMessage1 retVal = ((Lab4_Client.Lab4Service.SimplexSoap)(this)).Concat(inValue);
            return retVal.ConcatMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.ConcatMessage1> Lab4_Client.Lab4Service.SimplexSoap.ConcatAsync(Lab4_Client.Lab4Service.ConcatMessage request) {
            return base.Channel.ConcatAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client.Lab4Service.ConcatMessage1> ConcatAsync(string s, double d) {
            Lab4_Client.Lab4Service.ConcatMessage inValue = new Lab4_Client.Lab4Service.ConcatMessage();
            inValue.s = s;
            inValue.d = d;
            return ((Lab4_Client.Lab4Service.SimplexSoap)(this)).ConcatAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4_Client.Lab4Service.SumMessage1 Lab4_Client.Lab4Service.SimplexSoap.Sum(Lab4_Client.Lab4Service.SumMessage request) {
            return base.Channel.Sum(request);
        }
        
        public Lab4_Client.Lab4Service.A Sum(Lab4_Client.Lab4Service.A a1, Lab4_Client.Lab4Service.A a2) {
            Lab4_Client.Lab4Service.SumMessage inValue = new Lab4_Client.Lab4Service.SumMessage();
            inValue.a1 = a1;
            inValue.a2 = a2;
            Lab4_Client.Lab4Service.SumMessage1 retVal = ((Lab4_Client.Lab4Service.SimplexSoap)(this)).Sum(inValue);
            return retVal.SumMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Lab4_Client.Lab4Service.SumMessage1> Lab4_Client.Lab4Service.SimplexSoap.SumAsync(Lab4_Client.Lab4Service.SumMessage request) {
            return base.Channel.SumAsync(request);
        }
        
        public System.Threading.Tasks.Task<Lab4_Client.Lab4Service.SumMessage1> SumAsync(Lab4_Client.Lab4Service.A a1, Lab4_Client.Lab4Service.A a2) {
            Lab4_Client.Lab4Service.SumMessage inValue = new Lab4_Client.Lab4Service.SumMessage();
            inValue.a1 = a1;
            inValue.a2 = a2;
            return ((Lab4_Client.Lab4Service.SimplexSoap)(this)).SumAsync(inValue);
        }
    }
}
